#!/usr/bin/env python3
"""PC42: source-faithful STATIC first-pose atlas, not another limb offset.

Extracts the approved male EAST rifle foreground from the committed reference,
then partitions its *original RGB pixels* into independent anatomical/weapon
layers without interpolating new anatomy. Pose pivots are explicit and authored
in approved-reference pixel space. The composite is mathematically lossless
against the extracted foreground: every original nonzero-alpha source pixel
is assigned to exactly one sprite layer.

The layers are PROVISIONAL segmentation and must undergo human visual QA.
NO motion, weapon aiming, new gender assets, or APK generated by this script.
"""
from pathlib import Path
import json, sys
import cv2
import numpy as np
from PIL import Image,ImageDraw,ImageFilter,ImageChops,ImageStat

repo=Path(__file__).resolve().parents[1]
root=repo/"pc42-static-prototype"
out=root/"assets"
parts=out/"parts"
parts.mkdir(parents=True,exist_ok=True)
source=repo/"assets/authored2d/unified_character/rig/reference/male_east_rifle.png"
original=Image.open(source).convert("RGB")
assert original.size == (310,315),f"Unexpected reference size {original.size}"
# One authoritative top panel only, without label, border, or neighboring view.
W,H=236,254
crop=original.crop((0,0,W,H))
rgb=np.array(crop,dtype=np.uint8)
# Semantic probability matte; only approved source pixels become the new art.
seg=np.zeros((H,W),np.uint8)
cv2.rectangle(seg,(46,5),(225,252),cv2.GC_PR_BGD,-1)
regions=[
 [(88,7),(117,4),(141,18),(144,50),(124,64),(98,57)],
 [(49,55),(67,45),(85,37),(110,54),(124,107),(113,156),(65,162),(46,119)],
 [(85,66),(107,58),(140,70),(168,74),(180,89),(157,108),(124,125),(90,128)],
 [(85,109),(140,115),(149,171),(118,194),(90,186),(68,158)],
 [(68,169),(118,151),(154,171),(156,189),(142,232),(100,253),(57,249),(54,215)],
 [(126,61),(214,60),(227,73),(215,83),(151,91),(124,83)]
]
for poly in regions:
    cv2.fillPoly(seg,[np.asarray(poly,np.int32)],cv2.GC_PR_FGD)
# Only sparse, high-confidence interior pixels are sure FG.
for x,y in [(113,29),(106,42),(76,78),(72,110),(98,93),
            (116,116),(107,143),(93,165),(80,186),(76,221),
            (107,228),(130,189),(136,73),(154,72),(180,72)]:
    cv2.circle(seg,(x,y),1,cv2.GC_FGD,-1)
cv2.rectangle(seg,(0,0),(W-1,2),cv2.GC_BGD,-1)
seg[:,:40]=cv2.GC_BGD
seg[:,229:]=cv2.GC_BGD
try:
    cv2.grabCut(rgb,seg,None,np.zeros((1,65),np.float64),
                np.zeros((1,65),np.float64),6,cv2.GC_INIT_WITH_MASK)
except cv2.error as exc:
    raise RuntimeError(f"PC42 reference foreground segmentation failed: {exc}")
mask=np.where((seg==cv2.GC_FGD)|(seg==cv2.GC_PR_FGD),255,0).astype(np.uint8)
# Reject disconnected specks, but preserve weapon barrel narrow components.
count,labels,stats,_=cv2.connectedComponentsWithStats(mask,8)
valid=np.zeros_like(mask)
for i in range(1,count):
    x,y,w,h,area=map(int,stats[i])
    if area>=5 and x>=43 and x+w<=229:
        valid[labels==i]=255
# GrabCut alone discards near-black authored hair tips and the distal rifle
# barrel because these RGB values resemble the dark painted background.
# Restore ONLY pixels that demonstrably differ from same-row background
# samples inside narrow human-identified source silhouette regions.
background=np.median(np.concatenate([rgb[:,5:35,:],rgb[:,228:235,:]],axis=1).astype(np.int16),axis=1)
delta=np.max(np.abs(rgb.astype(np.int16)-background[:,None,:]),axis=2)
restored={}
for name,points,threshold,kernel in [
    ("hair",[(86,5),(130,5),(144,25),(140,57),(104,57),(87,36)],7,(2,2)),
    ("rifle_muzzle",[(165,60),(210,61),(224,70),(225,90),(186,94),(167,84)],6,(3,3))
]:
    bound=np.zeros((H,W),np.uint8)
    cv2.fillPoly(bound,[np.asarray(points,np.int32)],1)
    certainty=((delta>threshold)&(bound>0)).astype(np.uint8)
    certainty=cv2.morphologyEx(certainty,cv2.MORPH_CLOSE,np.ones(kernel,np.uint8))
    n,lbl,stats,_=cv2.connectedComponentsWithStats(certainty,8)
    for component in range(1,n):
        if int(stats[component,cv2.CC_STAT_AREA])<3:
            certainty[lbl==component]=0
    restored[name]=int(np.count_nonzero((certainty>0)&(valid==0)))
    valid[certainty>0]=255
# Source image is 2D low-resolution; feather only cutout boundary subpixel.
alpha=np.array(Image.fromarray(valid,"L").filter(ImageFilter.GaussianBlur(.48)))
alpha[np.asarray(valid)==255]=np.maximum(alpha[np.asarray(valid)==255],240)
if np.count_nonzero(alpha>0)<3500:raise RuntimeError("PC42 foreground too small, requires review")
source_rgba=Image.fromarray(np.dstack((rgb,alpha)),"RGBA")
source_rgba.save(out/"approved_foreground_matte.png")
crop.save(out/"approved_reference_panel.png")
# Part ownership is semantic / joint-aware, and always EXCLUSIVE.
# Geometry is not regenerated: all RGB samples come from approved screenshot.
layers=[
 ("far_arm",[(102,72),(123,74),(144,80),(150,95),(135,110),(107,115),(98,96)],(105,79)),
 ("rear_rifle_stock",[(117,59),(146,57),(156,66),(158,78),(126,87),(118,82)],(129,73)),
 ("backpack",[(53,48),(95,34),(115,62),(114,110),(109,151),(79,172),(50,144),(45,80)],(88,95)),
 ("back_shin",[(112,171),(145,162),(154,197),(145,226),(157,235),(156,249),(118,251),(112,220)],(125,207)),
 ("front_shin",[(62,170),(109,174),(107,221),(116,242),(105,253),(50,253),(54,225)],(84,213)),
 ("back_thigh",[(104,138),(145,136),(155,174),(142,204),(112,203),(105,183)],(122,169)),
 ("front_thigh",[(79,133),(119,132),(126,163),(107,198),(69,190),(66,159)],(99,165)),
 ("pelvis",[(87,125),(142,119),(147,161),(101,172),(75,157)],(110,150)),
 ("torso",[(81,56),(130,51),(146,91),(139,142),(96,149),(78,113)],(111,102)),
 ("near_upper_arm",[(90,68),(119,63),(134,89),(127,117),(109,133),(93,118),(85,91)],(102,78)),
 ("near_forearm",[(108,105),(133,92),(165,73),(173,92),(143,109),(125,131)],(120,115)),
 ("head_neck",[(86,5),(144,4),(143,60),(120,71),(93,58)],(118,59)),
 ("rifle_receiver",[(126,56),(228,56),(229,91),(150,93),(124,84)],(136,75)),
 ("trigger_hand",[(124,72),(150,65),(151,91),(130,99),(122,88)],(135,84)),
 ("support_hand",[(150,64),(183,64),(186,92),(155,98)],(166,80))
]
# Assign from frontmost to backmost to avoid double painting:
# partition at anatomical boundaries (foreground pixels always retained).
parts_data={}
remaining=(alpha>0)
for name,points,pivot in reversed(layers):
    domain=np.zeros((H,W),np.uint8)
    cv2.fillPoly(domain,[np.asarray(points,np.int32)],1)
    belongs=remaining & (domain>0)
    remaining[belongs]=False
    parts_data[name]=np.where(belongs,alpha,0).astype(np.uint8)
# Any pixels not falling inside a provisional body polygon go into a real
# source-derived "unclassified detail" layer rather than being discarded.
parts_data["source_detail_unassigned"]=np.where(remaining,alpha,0).astype(np.uint8)
assert np.array_equal(sum((a.astype(np.uint16) for a in parts_data.values()),
                          np.zeros((H,W),np.uint16)),alpha.astype(np.uint16))
manifest={"schema":"pc42-static-reference-layers-v1",
          "source":str(source.relative_to(repo)),
          "phase":"male_right_static_rifle_ONLY",
          "status":"PROVISIONAL_SEGMENTATION_VISUAL_QA_REQUIRED",
          "image_size":[W,H],"original_reference_size":list(original.size),
          "part_count":len(parts_data),"pixel_rule":"exclusive alpha ownership; no RGB changes",
          "ordering":[name for name,_,_ in layers]+["source_detail_unassigned"],
          "segments":[]}
pivots={name:list(piv) for name,points,piv in layers}
pivots["source_detail_unassigned"]=[112,145]
layer_objs=[]
for name in manifest["ordering"]:
    m=parts_data[name]
    layer=Image.fromarray(np.dstack((rgb,m)),"RGBA")
    filename=f"{name}.png"
    layer.save(parts/filename)
    entry={"name":name,"filename":"parts/"+filename,"pivot":pivots[name],
           "opaque_pixels":int(np.count_nonzero(m>0)),
           "visual_qa":"UNREVIEWED"}
    manifest["segments"].append(entry)
    layer_objs.append(layer)
out.joinpath("manifest.json").write_text(json.dumps(manifest,indent=2)+"\n")
composed=Image.new("RGBA",(W,H),(0,0,0,0))
for layer in layer_objs:
    # Since layers have disjoint alpha, paste at exact pixel coordinates.
    composed.alpha_composite(layer)
composed.save(out/"reconstructed_static_pose.png")
# Transparent RGB values are undefined under alpha compositing.
a0=np.asarray(composed); a1=np.asarray(source_rgba)
visible=a1[:,:,3]>0
if not np.array_equal(a0[:,:,3],a1[:,:,3]) or not np.array_equal(a0[:,:,:3][visible],a1[:,:,:3][visible]):
    raise RuntimeError("PC42 reconstructed visible original RGB/alpha mismatch")
mask_review=Image.new("RGB",(W*3,H+26),(20,23,26))
for i,img in enumerate((crop,source_rgba,composed)):
    if i==0:mask_review.paste(img,(i*W,26))
    else:mask_review.paste(img,(i*W,26),img)
d=ImageDraw.Draw(mask_review)
for i,title in enumerate(("Approved reference","Cutout alpha mask","Anatomical layer composite")):
    d.text((i*W+4,6),title,fill=(220,220,220))
mask_review.save(out/"matte_review.png")
print(f"PC42_SOURCE_FAITHFUL_STATIC: {len(parts_data)} source-derived parts, {int(np.count_nonzero(alpha))} nonzero-alpha pixels, recovered hair+barrel RGB={restored}, exact per-pixel compositing PASS")
print("PC42 visual/articulated/anatomy acceptance remains PENDING; independent Godot capture required.")
