#!/usr/bin/env python3
"""PC42: source-faithful STATIC first-pose atlas, not another limb offset.

Extracts the approved male EAST rifle foreground from the committed reference,
then partitions its *original RGB pixels* into independent anatomical/weapon
layers without interpolating new anatomy. Pose pivots are explicit and authored
in approved-reference pixel space. The composite is mathematically lossless
against the extracted foreground: every original nonzero-alpha source pixel
is assigned to exactly one sprite layer.

The layers are PROVISIONAL segmentation and must undergo human visual QA.
NO motion, weapon aiming, new gender assets, or APK generated by this script.
"""
from pathlib import Path
import json, sys
import cv2
import numpy as np
from PIL import Image,ImageDraw,ImageFilter,ImageChops,ImageStat

repo=Path(__file__).resolve().parents[1]
root=repo/"pc42-static-prototype"
out=root/"assets"
parts=out/"parts"
parts.mkdir(parents=True,exist_ok=True)
source=repo/"assets/authored2d/unified_character/rig/reference/male_east_rifle.png"
original=Image.open(source).convert("RGB")
assert original.size == (310,315),f"Unexpected reference size {original.size}"
# One authoritative top panel only, without label, border, or neighboring view.
W,H=236,254
crop=original.crop((0,0,W,H))
rgb=np.array(crop,dtype=np.uint8)
# Semantic probability matte; only approved source pixels become the new art.
seg=np.zeros((H,W),np.uint8)
cv2.rectangle(seg,(46,5),(225,252),cv2.GC_PR_BGD,-1)
regions=[
 [(88,7),(117,4),(141,18),(144,50),(124,64),(98,57)],
 [(49,55),(67,45),(85,37),(110,54),(124,107),(113,156),(65,162),(46,119)],
 [(85,66),(107,58),(140,70),(168,74),(180,89),(157,108),(124,125),(90,128)],
 [(85,109),(140,115),(149,171),(118,194),(90,186),(68,158)],
 [(68,169),(118,151),(154,171),(156,189),(142,232),(100,253),(57,249),(54,215)],
 [(126,61),(214,60),(227,73),(215,83),(151,91),(124,83)]
]
for poly in regions:
    cv2.fillPoly(seg,[np.asarray(poly,np.int32)],cv2.GC_PR_FGD)
# Only sparse, high-confidence interior pixels are sure FG.
for x,y in [(113,29),(106,42),(76,78),(72,110),(98,93),
            (116,116),(107,143),(93,165),(80,186),(76,221),
            (107,228),(130,189),(136,73),(154,72),(180,72)]:
    cv2.circle(seg,(x,y),1,cv2.GC_FGD,-1)
cv2.rectangle(seg,(0,0),(W-1,2),cv2.GC_BGD,-1)
seg[:,:40]=cv2.GC_BGD
seg[:,229:]=cv2.GC_BGD
try:
    cv2.grabCut(rgb,seg,None,np.zeros((1,65),np.float64),
                np.zeros((1,65),np.float64),6,cv2.GC_INIT_WITH_MASK)
except cv2.error as exc:
    raise RuntimeError(f"PC42 reference foreground segmentation failed: {exc}")
mask=np.where((seg==cv2.GC_FGD)|(seg==cv2.GC_PR_FGD),255,0).astype(np.uint8)
# Reject disconnected specks, but preserve weapon barrel narrow components.
count,labels,stats,_=cv2.connectedComponentsWithStats(mask,8)
valid=np.zeros_like(mask)
for i in range(1,count):
    x,y,w,h,area=map(int,stats[i])
    if area>=5 and x>=43 and x+w<=229:
        valid[labels==i]=255
# GrabCut alone discards near-black authored hair tips and the distal rifle
# barrel because these RGB values resemble the dark painted background.
# Restore ONLY pixels that demonstrably differ from same-row background
# samples inside narrow human-identified source silhouette regions.
background=np.median(np.concatenate([rgb[:,5:35,:],rgb[:,228:235,:]],axis=1).astype(np.int16),axis=1)
delta=np.max(np.abs(rgb.astype(np.int16)-background[:,None,:]),axis=2)
restored={}
for name,points,threshold,kernel in [
    ("hair",[(86,5),(130,5),(144,25),(140,57),(104,57),(87,36)],7,(2,2)),
    ("rifle_muzzle",[(165,60),(210,61),(224,70),(225,90),(186,94),(167,84)],6,(3,3))
]:
    bound=np.zeros((H,W),np.uint8)
    cv2.fillPoly(bound,[np.asarray(points,np.int32)],1)
    certainty=((delta>threshold)&(bound>0)).astype(np.uint8)
    certainty=cv2.morphologyEx(certainty,cv2.MORPH_CLOSE,np.ones(kernel,np.uint8))
    n,lbl,stats,_=cv2.connectedComponentsWithStats(certainty,8)
    for component in range(1,n):
        if int(stats[component,cv2.CC_STAT_AREA])<3:
            certainty[lbl==component]=0
    restored[name]=int(np.count_nonzero((certainty>0)&(valid==0)))
    valid[certainty>0]=255
# Source image is 2D low-resolution; feather only cutout boundary subpixel.
alpha=np.array(Image.fromarray(valid,"L").filter(ImageFilter.GaussianBlur(.48)))
alpha[np.asarray(valid)==255]=np.maximum(alpha[np.asarray(valid)==255],240)
if np.count_nonzero(alpha>0)<3500:raise RuntimeError("PC42 foreground too small, requires review")
source_rgba=Image.fromarray(np.dstack((rgb,alpha)),"RGBA")
source_rgba.save(out/"approved_foreground_matte.png")
crop.save(out/"approved_reference_panel.png")
# Part ownership is semantic / joint-aware, and always EXCLUSIVE.
# Geometry is not regenerated: all RGB samples come from approved screenshot.
# Only visible source artwork is extracted. Far arm segments fully covered
# by torso/weapon are NOT fabricated; reconstruction of the invisible geometry
# will use approved companion arm sprites at the subsequent motion gate.
layers=[
 ("head_neck",[(88,6),(136,6),(141,29),(138,56),(116,68),(91,62)],(118,59)),
 ("dominant_hand",[(123,73),(143,73),(149,91),(132,99),(121,87)],(134,84)),
 ("support_hand",[(157,72),(180,69),(185,91),(155,94)],(170,81)),
 ("near_forearm",[(118,80),(140,77),(145,92),(130,108),(115,105)],(120,103)),
 ("near_upper_arm",[(89,57),(117,56),(128,72),(121,98),(109,111),(89,93)],(104,78)),
 ("rifle_stock",[(119,59),(142,58),(144,76),(121,81)],(129,71)),
 ("rifle_receiver",[(131,59),(225,68),(225,92),(182,90),(180,83),(143,82),(142,88),(136,81)],(153,70)),
 ("torso",[(82,47),(130,47),(138,96),(139,144),(89,143),(79,96)],(114,105)),
 ("backpack",[(45,43),(98,37),(110,66),(103,126),(90,143),(49,134)],(76,95)),
 ("pelvis",[(78,126),(135,124),(146,158),(121,165),(84,167)],(112,140)),
 ("front_thigh",[(70,139),(108,137),(121,169),(107,188),(73,191),(69,162)],(88,160)),
 ("back_thigh",[(104,142),(143,135),(159,171),(146,185),(110,185)],(132,155)),
 ("front_shin",[(64,170),(110,167),(111,203),(95,241),(64,252),(50,226)],(79,182)),
 ("back_shin",[(114,172),(151,159),(154,195),(159,229),(112,232)],(131,184)),
]
# Priority is frontmost first. At the static pose every foreground pixel
# belongs to exactly one genuinely drawn visible part.
parts_data={}
remaining=(alpha>0)
for name,points,pivot in layers:
    domain=np.zeros((H,W),np.uint8)
    cv2.fillPoly(domain,[np.asarray(points,np.int32)],1)
    belongs=remaining & (domain>0)
    remaining[belongs]=False
    parts_data[name]=np.where(belongs,alpha,0).astype(np.uint8)
# Tiny edge fragments beyond provisional hand-drawn anatomical envelopes
# follow the closest actual visible part. No orphan procedural filler sprite
# may be moved independently in a later skeletal animation.
if remaining.any():
    maps=[]
    names=list(parts_data)
    for name in names:
        occupied=(parts_data[name]>0)
        if not occupied.any():raise RuntimeError("PC42 authored body segment empty: "+name)
        maps.append(cv2.distanceTransform((~occupied).astype(np.uint8),cv2.DIST_L2,3))
    nearest=np.argmin(np.stack(maps,axis=0),axis=0)
    for i,name in enumerate(names):
        belongs=remaining & (nearest==i)
        parts_data[name][belongs]=alpha[belongs]
essential={"near_upper_arm":700,"near_forearm":120,"rifle_stock":70,
           "rifle_receiver":450,"torso":1200,"head_neck":900,
           "dominant_hand":120,"support_hand":120,"backpack":700,
           "front_shin":600,"back_shin":200}
for name,minimum in essential.items():
    count=int(np.count_nonzero(parts_data[name]>0))
    if count<minimum:
        raise RuntimeError(f"PC42 {name} semantic layer underfilled {count}<{minimum}")
assert np.array_equal(sum((a.astype(np.uint16) for a in parts_data.values()),
                          np.zeros((H,W),np.uint16)),alpha.astype(np.uint16))
manifest={"schema":"pc42-static-reference-layers-v1",
          "source":str(source.relative_to(repo)),
          "phase":"male_right_static_rifle_ONLY",
          "status":"PROVISIONAL_SEGMENTATION_VISUAL_QA_REQUIRED",
          "image_size":[W,H],"original_reference_size":list(original.size),
          "part_count":len(parts_data),"pixel_rule":"exclusive alpha ownership; no RGB changes",
          "ordering":[name for name,_,_ in layers],
          "covered_not_synthesized":["far_arm_upper","far_arm_forearm"],
          "segments":[]}
pivots={name:list(piv) for name,points,piv in layers}
layer_objs=[]
for name in manifest["ordering"]:
    m=parts_data[name]
    layer=Image.fromarray(np.dstack((rgb,m)),"RGBA")
    filename=f"{name}.png"
    layer.save(parts/filename)
    entry={"name":name,"filename":"parts/"+filename,"pivot":pivots[name],
           "opaque_pixels":int(np.count_nonzero(m>0)),
           "visual_qa":"UNREVIEWED"}
    manifest["segments"].append(entry)
    layer_objs.append(layer)
out.joinpath("manifest.json").write_text(json.dumps(manifest,indent=2)+"\n")
composed=Image.new("RGBA",(W,H),(0,0,0,0))
for layer in layer_objs:
    # Since layers have disjoint alpha, paste at exact pixel coordinates.
    composed.alpha_composite(layer)
composed.save(out/"reconstructed_static_pose.png")
# Transparent RGB values are undefined under alpha compositing.
a0=np.asarray(composed); a1=np.asarray(source_rgba)
visible=a1[:,:,3]>0
if not np.array_equal(a0[:,:,3],a1[:,:,3]) or not np.array_equal(a0[:,:,:3][visible],a1[:,:,:3][visible]):
    raise RuntimeError("PC42 reconstructed visible original RGB/alpha mismatch")
mask_review=Image.new("RGB",(W*3,H+26),(20,23,26))
for i,img in enumerate((crop,source_rgba,composed)):
    if i==0:mask_review.paste(img,(i*W,26))
    else:mask_review.paste(img,(i*W,26),img)
d=ImageDraw.Draw(mask_review)
for i,title in enumerate(("Approved reference","Cutout alpha mask","Anatomical layer composite")):
    d.text((i*W+4,6),title,fill=(220,220,220))
mask_review.save(out/"matte_review.png")
print(f"PC42_SOURCE_FAITHFUL_STATIC: {len(parts_data)} source-derived parts, {int(np.count_nonzero(alpha))} nonzero-alpha pixels, recovered hair+barrel RGB={restored}, exact per-pixel compositing PASS")
print("PC42 visual/articulated/anatomy acceptance remains PENDING; independent Godot capture required.")
